### ISSUE TITLE
Does not respect a user-land failed (context.fail) lambda invocation 

### ISSUE THREAD

**Issue by AndrewBarba** [Blissfully/sqs-lambda-bridge#5]
Right now all invocations of our lambdas are considered "successful" even if we call `context.fail()` or `callback(new Error(...))`. I think this is because there is a difference between `lambda.invoke(options, cb)` returning an error in that callback, meaning the invoke could not be done, and the invoke being done but the actual lambda failing during the invoke. In the latter case there will be no error object but there will be a `data.FunctionError` as seen here: https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Lambda.html#invoke-property

That should be checked and then passed to `sqs-consumer`

**Comment by jelder** [comment]
Good catch! Would you be interested in providing a PR?

**Comment by AndrewBarba** [comment]
I guess... https://github.com/Blissfully/sqs-lambda-bridge/pull/6

**Comment by AndrewBarba** [comment]
Thanks for merging! Do you need to bump version and republish? Or does it pull from git master branch?

**Comment by jelder** [comment]
Thanks @AndrewBarba I appreciate it. Hope you're finding this project useful.
